# You are given two strings s and t. 
# String t is generated by randomly shuffling string s
#  and then adding one more letter at a random position.
#   Return the letter that was added to t.

# Examples
# find_the_difference("abcd", "abcde") ➞ "e"

# find_the_difference("", "y") ➞ "y"

# find_the_difference("ae", "aea") ➞ "a"



# def find_the_difference(s, t)
# 	s_array = s.chars
# 	t_array = t.chars
#   difference = t_array.each_with_index.map do |letter, index|
#     if letter == s_array[index]
#       next
#     else
#      letter
#     end
#   end
#   difference.compact.first
# end
def find_the_difference(s,t)
  new_s = s.chars
  new_t = t.chars
  new_s.each do |letter|
    if new_t.include?(letter)
      t_index = new_t.index(letter)
      new_t.delete_at(t_index)
    else
      next
    end
  end
  new_t.first
end

s = ""
t = "y"
p find_the_difference(s, t)